### ISSUE TITLE
Is there any way to download NPM?

### ISSUE THREAD

**Issue by tiagoboeing** [ehmicky/get-node#13]
When download and caching `Node` on `output` path, only the Node executable it's available in something like: `16.17.0/x64/bin/node`

Not include the NPM, is this intentional? I'm trying to download and install the Node... and execute NPM scripts. 

The NPM usually be available on the "same" path than Node, only being necessary to back one step `../npm`

**Comment by ehmicky** [comment]
Hi @tiagoboeing,

Yes, this is intentional. Installing npm is unfortunately out of the scope of `get-node` which only focuses on the Node.js binary.

Conceptually, `get-node` treats `npm` and other package managers more like a dependency than a core part of Node.js. This is because `get-node` was initially designed [for `nve`](https://github.com/ehmicky/nve) which is meant for one-off command execution, as opposed to machine-wide Node.js installation.

If you are trying to install both Node.js and `npm` on a machine, I would advise either:
  - Using `get-node` together with [Corepack](https://github.com/nodejs/corepack). Please note that Corepack requires either Node.js or `npm`, so this will only allow you to install specific versions of `npm` on a machine which already has Node.js or `npm`.  
  - Using `nvm` or similar package managers instead

**Comment by tiagoboeing** [comment]
> Hi @tiagoboeing,
> 
> Yes, this is intentional. Installing npm is unfortunately out of the scope of `get-node` which only focuses on the Node.js binary.
> 
> Conceptually, `get-node` treats `npm` and other package managers more like dependencies than a core part of Node.js. This is because `get-node` was initially designed [for `nve`](https://github.com/ehmicky/nve) which is meant for one-off command execution, as opposed to machine-wide Node.js installation.
> 
> If you are trying to install both Node.js and `npm` on a machine, I would advise either:
> 
> * Using `get-node` together with [Corepack](https://github.com/nodejs/corepack). Please note that Corepack requires either Node.js or `npm`, so this will only allow you to install specific versions of `npm` on a machine which already has Node.js or `npm`.
> * Using `nvm` or similar package managers instead

Thanks for the explanation, I'll follow the specified way to install Node and NPM together. 😁

**Comment by ehmicky** [comment]
If you found a convenient way to make it work with `get-node`, please let me know!
If not, no worries. Thanks for reaching out :+1:

**Comment by tiagoboeing** [comment]
For my purposes, looks like your other project ([`nve`](https://github.com/ehmicky/nve)) will works fine. I'm creating a GitHub Action to execute NPM scripts using a specified Node version on inputs.

The install process will be dispatched using child process through [`@actions/exec`](https://github.com/actions/toolkit/tree/main/packages/exec).

**Comment by ehmicky** [comment]
Great! You might want to check out [`nvexeca`](https://github.com/ehmicky/nvexeca) too, which is the programmatic module used by `nve`. It basically combines `get-node` and [`execa`](https://github.com/sindresorhus/execa). `@actions/exec` and `execa` are mostly doing the same thing (arguably `execa` is doing a little more, but I am biased :) ).
