### ISSUE TITLE
Fetch binaries from actions/node-versions

### ISSUE THREAD

**Issue by privatenumber** [ehmicky/get-node#25]
### Guidelines

- [X] Please search other issues to make sure this feature has not already been requested.

### Which problem is this feature request solving?

I run `get-node` on GitHub CI a lot, and sometimes the official Node.js server is slow or errors.

### Describe the solution you'd like

The option to fetch from https://github.com/actions/node-versions

I noticed https://github.com/actions/setup-node downloads the Node.js binaries from https://github.com/actions/node-versions release artifacts, probably because the server is closer and faster:

<img width="786" src="https://github.com/ehmicky/get-node/assets/1075694/8521e3d7-39e2-4aef-a8f4-a5c0530cd90a">

### Pull request (optional)

- [ ] I can submit a pull request.

**Comment by ehmicky** [comment]
Hi @privatenumber,

The main difference with the GitHub actions is that they use the [following manifest file](https://raw.githubusercontent.com/actions/node-versions/main/versions-manifest.json) instead of the [official Node.js one](https://nodejs.org/dist/index.json), with the same Node.js binary files but hosted on GitHub.

Some difference: it does not support less mainstream architectures (AIX, x86, ARM, PPC64, s390). It also only goes back to Node 6.17.1.

It is possible that `raw.githubusercontent.com` has a lower latency than `nodejs.org/dist`, especially from a GitHub action. More importantly, those Node versions files are cached and [retrieved](https://github.com/actions/setup-node/blob/5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d/src/distributions/official_builds/official_builds.ts#L149) using [`@actions/tool-cache`](https://github.com/actions/toolkit/blob/main/packages/tool-cache/README.md).

I agree this would result in a better experience (faster and fewer download errors) when using `get-node` inside GitHub actions. However, implementing this would require significant changes to multiple repositories. Also, most of the logic would duplicate the implementation from `setup-node`.

Which leads me to ask you: can you tell me more about how you use `get-node` inside GitHub actions? 
Also: why not use `setup-node` instead?

**Comment by privatenumber** [comment]
In a few of my projects, I test multiple Node.js versions in one job like this:
https://github.com/esbuild-kit/tsx/blob/f8837b72793131042f7fc58e2282ac2dc1a86184/tests/index.ts#L34

It's possible to move the logic to setup-node, but I'd have to move the testing logic to the GitHub Actions yml file, and it would complicate testing locally.

Personally, I like that I can see all the testing logic in JS, and run them between CI and local with one command.

Since it's a major change and the Github distribution isn't a true mirror, I think it's completely reasonable to close this issue. I really appreciate your thorough evaluation nonetheless!

**Comment by ehmicky** [comment]
Thanks a lot for the information and link to your code @privatenumber.

This seems to be a good use case. For most users, I would recommend using `@actions/setup-node` instead of `get-node` and putting the logic in the GitHub Actions workflow file. However, I can see why you might want to put it in the test instead, as it gives you additional flexibility.

### Download speed

I ran some benchmarks trying to `fetch(nodeUrl)` using either `nodejs.org/dist` or the URL from GitHub `node-versions`. (For more details, here are the links to the [code](https://github.com/ehmicky/eslint-config/blob/5460a1dbb8a3949619408e1c5d34dfcb3cd52bb7/src/main.test.js#L25) and [results](https://github.com/ehmicky/eslint-config/actions/runs/6284696003/job/17066322981#logs)).
 
The following shows the mean duration per download, after fetching the Node.js `20.7.0` archive 10 times in a row.
  - When run locally with `nodejs.org/dist`: Linux: 62ms, macOS: 45ms, Windows: 52ms
  - When run in GitHub actions with `nodejs.org/dist`: Linux: 58ms, macOS: 92ms, Windows: 62ms
  - When run locally with the URL from GitHub `node-versions`: Linux: 286ms, macOS: 239ms, Windows: 243ms
  - When run in GitHub actions with the URL from GitHub `node-versions`: Linux: 137ms, macOS: 130ms, Windows: 132ms

So, surprisingly, it turns out fetching Node.js from `nodejs.org/dist` is _much_ faster than using GitHub `node-versions` even inside GitHub actions! 

### Caching

GitHub `node-versions` also uses the GitHub actions cache to remove the need to download the Node.js binary. From previous experience, I remembered it not to be as fast as one might expect. I think this might be due to the need to download the cached assets at the beginning of the workflow, and to run the additional caching logic.

That being said, caching also provides with resilience. Namely, `nodejs.org/dist` can be a little unstable and sometimes fails.  

However, `get-node` provides some solutions to this. First, download failures are automatically retried twice. 

Also, `get-node` has some built-in caching logic: when running it multiple times with the same output path, only the first call will download the Node.js binary. More precisely, if the specific Node.js version already exists in the output path, it is used instead of re-downloading the Node.js binary. 

https://github.com/ehmicky/get-node/blob/0e7f4cb1f256ca40eae62a13d4f6789856766cd9/src/download.js#L16-L20

### Recommendations

I am wondering whether a good approach for your case would be to edit your GitHub actions workflow file to [make it cache](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows) the Node.js binaries output path? In other words `fixture.path` in:

https://github.com/esbuild-kit/tsx/blob/f8837b72793131042f7fc58e2282ac2dc1a86184/tests/index.ts#L34

What are your thoughts on this?

**Comment by privatenumber** [comment]
Very interesting investigation! Thanks for gathering this data. I'm surprised downloading from GitHub releases is slower even for GitHub Actions.

Node's server is generally fast for me, but what prompted me to investigate this was locally downloading from Node's server was really slow a few times last week (maybe it was PST work hours and congested?) and I was speculating it to cause the tests to freeze.

I started caching the nve cache directory like this, which seems effective:
https://github.com/esbuild-kit/tsx/blob/f8837b72793131042f7fc58e2282ac2dc1a86184/.github/workflows/test.yml#L44-L46

**Comment by ehmicky** [comment]
Yes, that's exactly it! Thanks for sharing the setup @privatenumber.
